/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "check_s21_string.check" instead.
 */

#include <check.h>

#line 1 "check_s21_string.check"
#include<stdio.h>
#include<string.h>
#include<stdlib.h>
#include"s21_string.h"

START_TEST(memcmp_1)
{
#line 7
char str1[] = "123456";
char str2[] = "123456";
size_t a = 10;
ck_assert_int_eq(memcmp(str1, str2, a), s21_memcmp(str1, str2, a));

}
END_TEST

START_TEST(memcmp_2)
{
#line 13
char str1[] = "654321";
char str2[] = "123456";
size_t a = 10;
ck_assert_int_eq(memcmp(str1, str2, a), s21_memcmp(str1, str2, a));

}
END_TEST

START_TEST(memcmp_3)
{
#line 19
char str1[] = "";
char str2[] = "";
size_t a = 10;
ck_assert_int_eq(memcmp(str1, str2, a), s21_memcmp(str1, str2, a));

}
END_TEST

START_TEST(memcmp_4)
{
#line 25
char str1[] = "abc321";
char str2[] = "abc456";
size_t a = 10;
ck_assert_int_eq(memcmp(str1, str2, a), s21_memcmp(str1, str2, a));

}
END_TEST

START_TEST(memcmp_5)
{
#line 31
char str1[] = "abcd";
char str2[] = "abcdx";
size_t a = 6;
ck_assert_int_eq(memcmp(str1, str2, a), s21_memcmp(str1, str2, a));

}
END_TEST

START_TEST(memcmp_6)
{
#line 37
char str1[] = "abcd";
char str2[] = "abcdx";
size_t a = 5;
ck_assert_int_eq(memcmp(str1, str2, a), s21_memcmp(str1, str2, a));

}
END_TEST

START_TEST(memcmp_7)
{
#line 43
char str1[] = "abcde";
char str2[] = "abcd";
size_t a = 4;
ck_assert_int_eq(memcmp(str1, str2, a), s21_memcmp(str1, str2, a));

}
END_TEST

START_TEST(memcmp_8)
{
#line 49
char str1[] = "ab";
char str2[] = "abc";
size_t a = 3;
ck_assert_int_eq(memcmp(str1, str2, a), s21_memcmp(str1, str2, a));

}
END_TEST

START_TEST(memmove_1)
{
#line 55
char str1[] = "abc";
char str2[] = "123";
size_t a = 3;
ck_assert_ptr_eq(memmove(str1, str2, a), s21_memmove(str1, str2, a));
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, memcmp_1);
    tcase_add_test(tc1_1, memcmp_2);
    tcase_add_test(tc1_1, memcmp_3);
    tcase_add_test(tc1_1, memcmp_4);
    tcase_add_test(tc1_1, memcmp_5);
    tcase_add_test(tc1_1, memcmp_6);
    tcase_add_test(tc1_1, memcmp_7);
    tcase_add_test(tc1_1, memcmp_8);
    tcase_add_test(tc1_1, memmove_1);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
